apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-server
  template:
    metadata:
      labels:
        app: database-server
    spec:
      containers:
      - name: database-server
        image: caliberly-database-server-image:latest
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
    app: database-server
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
