apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
type: Opaque
data:
  # These values are placeholders, replace them with your actual secret ARNs
  secret-arn-username: dXNlcm5hbWU=
  secret-arn-password: cGFzc3dvcmQ=
